//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just4Us.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custommer
    {
        public int id { get; set; }
        public Nullable<int> idUser { get; set; }
        public string phoneNumber { get; set; }
        public string network { get; set; }
        public string cardCode { get; set; }
        public string cardSeri { get; set; }
        public string valueMoney { get; set; }
        public Nullable<System.DateTime> timeSubmit { get; set; }
    
        public virtual tblMember tblMember { get; set; }
    }
}
