//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just4Us.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Just4UsEntities : DbContext
    {
        public Just4UsEntities()
            : base("name=Just4UsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Custommer> Custommer { get; set; }
        public DbSet<KetQuaBac> KetQuaBac { get; set; }
        public DbSet<tbl_J4U_Wall> tbl_J4U_Wall { get; set; }
        public DbSet<tblArea> tblArea { get; set; }
        public DbSet<tblCategory> tblCategory { get; set; }
        public DbSet<tblContact> tblContact { get; set; }
        public DbSet<tblKetQuaNamTrung> tblKetQuaNamTrung { get; set; }
        public DbSet<tblMember> tblMember { get; set; }
        public DbSet<tblProduct> tblProduct { get; set; }
        public DbSet<tblSoxo> tblSoxo { get; set; }
        public DbSet<tblTinTuc> tblTinTuc { get; set; }
        public DbSet<tblTinhThanh> tblTinhThanh { get; set; }
        public DbSet<tblTypePro> tblTypePro { get; set; }
        public DbSet<tblThongBao> tblThongBao { get; set; }
        public DbSet<tblUser> tblUser { get; set; }
    }
}
