//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just4Us.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaBac
    {
        public int id { get; set; }
        public string maTinh { get; set; }
        public Nullable<System.DateTime> ngayMoXo { get; set; }
        public string loaiVe { get; set; }
        public string giaiDacBiet { get; set; }
        public string giaiNhat { get; set; }
        public string giaiNhi1 { get; set; }
        public string giaiNhi2 { get; set; }
        public string giaiBa1 { get; set; }
        public string giaiBa2 { get; set; }
        public string giaiBa3 { get; set; }
        public string giaiBa4 { get; set; }
        public string giaiBa5 { get; set; }
        public string giaiBa6 { get; set; }
        public string giaiTu1 { get; set; }
        public string giaiTu2 { get; set; }
        public string giaiTu3 { get; set; }
        public string giaiTu4 { get; set; }
        public string giaiNam1 { get; set; }
        public string giaiNam2 { get; set; }
        public string giaiNam3 { get; set; }
        public string giaiNam4 { get; set; }
        public string giaiNam5 { get; set; }
        public string giaiNam6 { get; set; }
        public string giaiSau1 { get; set; }
        public string giaiSau2 { get; set; }
        public string giaiSau3 { get; set; }
        public string giaiBay1 { get; set; }
        public string giaiBay2 { get; set; }
        public string giaiBay3 { get; set; }
        public string giaiBay4 { get; set; }
        public Nullable<int> mienXS { get; set; }
        public Nullable<int> idTinh { get; set; }
    
        public virtual tblTinhThanh tblTinhThanh { get; set; }
    }
}
