//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just4Us.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_J4U_Wall
    {
        public int ID { get; set; }
        public string status { get; set; }
        public string url { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
    }
}
