//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just4Us.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMember
    {
        public tblMember()
        {
            this.Custommer = new HashSet<Custommer>();
        }
    
        public int ID { get; set; }
        public string IDFacebook { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string UrlAvartar { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> RoleMember { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsRemove { get; set; }
    
        public virtual ICollection<Custommer> Custommer { get; set; }
    }
}
