//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just4Us.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> category { get; set; }
        public string sortContent { get; set; }
        public string longContent { get; set; }
        public string urlImage { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> typePro { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> viewed { get; set; }
        public Nullable<System.DateTime> dateadd { get; set; }
        public Nullable<bool> isRemove { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isHighlights { get; set; }
        public string urlImageSmall { get; set; }
    
        public virtual tblArea tblArea { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblTypePro tblTypePro { get; set; }
    }
}
