//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just4Us.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTypePro
    {
        public tblTypePro()
        {
            this.tblProduct = new HashSet<tblProduct>();
        }
    
        public int id { get; set; }
        public string typePromotion { get; set; }
    
        public virtual ICollection<tblProduct> tblProduct { get; set; }
    }
}
