//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just4Us.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTinTuc
    {
        public int id { get; set; }
        public string title { get; set; }
        public string des { get; set; }
        public string maincontent { get; set; }
        public string urlImage { get; set; }
        public Nullable<System.DateTime> dateadd { get; set; }
        public Nullable<bool> isremove { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string rewriteurl { get; set; }
        public string smallcontent { get; set; }
        public Nullable<bool> isVip { get; set; }
    }
}
