//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just4Us.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTinhThanh
    {
        public tblTinhThanh()
        {
            this.KetQuaBac = new HashSet<KetQuaBac>();
            this.tblKetQuaNamTrung = new HashSet<tblKetQuaNamTrung>();
        }
    
        public int ID { get; set; }
        public string MaTinh { get; set; }
        public string TenTinh { get; set; }
        public Nullable<int> ThuTrongTuan { get; set; }
        public Nullable<int> Mien { get; set; }
        public string Link { get; set; }
        public Nullable<int> ThuTrongTuan2 { get; set; }
    
        public virtual ICollection<KetQuaBac> KetQuaBac { get; set; }
        public virtual ICollection<tblKetQuaNamTrung> tblKetQuaNamTrung { get; set; }
    }
}
